//! Where captures live and how they are named.
//!
//! ```text
//! tests/fixtures/fingerprints/<provider>/
//!   captures/<YYYYMMDD-HHMMSS>-<endpoint>.json   fresh, scrubbed, git-ignored
//!   golden/<endpoint>.json                        blessed after review (committed)
//!   documented/<endpoint>.json                    the doc's columns as a capture (committed,
//!                                                 generated by the bluey-protocols tests)
//! ```

use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context};
use bluey_protocols::fingerprints::{scrub_capture, Capture, Provider, SCHEMA_VERSION};

/// Walk up from `start` to the repository root (the directory with `package.json`
/// and `tests/fixtures`) and return `tests/fixtures/fingerprints`.
pub fn fixtures_root_from(start: &Path) -> Option<PathBuf> {
    let mut dir = Some(start);
    while let Some(d) = dir {
        if d.join("package.json").is_file() && d.join("tests/fixtures").is_dir() {
            return Some(d.join("tests/fixtures/fingerprints"));
        }
        dir = d.parent();
    }
    None
}

/// `FINGERPRINTS_DIR` if set, else the repository's fixtures directory.
pub fn fixtures_root() -> anyhow::Result<PathBuf> {
    if let Some(dir) = std::env::var_os("FINGERPRINTS_DIR") {
        return Ok(PathBuf::from(dir));
    }
    let cwd = std::env::current_dir()?;
    fixtures_root_from(&cwd).ok_or_else(|| {
        anyhow!(
            "cannot find tests/fixtures/fingerprints above {} — run from the repository (bun run fingerprints:*) or set FINGERPRINTS_DIR",
            cwd.display()
        )
    })
}

pub fn captures_dir(root: &Path, provider: Provider) -> PathBuf {
    root.join(provider.id()).join("captures")
}

pub fn golden_dir(root: &Path, provider: Provider) -> PathBuf {
    root.join(provider.id()).join("golden")
}

pub fn documented_dir(root: &Path, provider: Provider) -> PathBuf {
    root.join(provider.id()).join("documented")
}

/// The endpoint name used in file names (`other` for paths the rules do not know).
pub fn endpoint_name(capture: &Capture) -> &'static str {
    Provider::parse(&capture.provider)
        .and_then(|p| {
            p.rules()
                .endpoint_for(&capture.request.method, &capture.request.path())
        })
        .map(|e| e.name)
        .unwrap_or("other")
}

fn timestamp_prefix(captured_at: &str) -> String {
    chrono::DateTime::parse_from_rfc3339(captured_at)
        .map(|t| t.with_timezone(&chrono::Utc))
        .unwrap_or_else(|_| chrono::Utc::now())
        .format("%Y%m%d-%H%M%S")
        .to_string()
}

pub fn read_capture(path: &Path) -> anyhow::Result<Capture> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let capture: Capture =
        serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
    if capture.schema > SCHEMA_VERSION {
        bail!(
            "{} uses capture schema {} but this build reads up to {SCHEMA_VERSION}",
            path.display(),
            capture.schema
        );
    }
    Ok(capture)
}

pub fn write_json(path: &Path, capture: &Capture) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let mut text = serde_json::to_string_pretty(capture)?;
    text.push('\n');
    std::fs::write(path, text).with_context(|| format!("writing {}", path.display()))
}

/// Write a fresh capture under `captures/`; never overwrites (suffixes `-2`, `-3`, …).
pub fn write_capture(root: &Path, capture: &Capture) -> anyhow::Result<PathBuf> {
    let provider = Provider::parse(&capture.provider)
        .ok_or_else(|| anyhow!("unknown provider {}", capture.provider))?;
    let dir = captures_dir(root, provider);
    let stem = format!(
        "{}-{}",
        timestamp_prefix(&capture.captured_at),
        endpoint_name(capture)
    );
    let mut path = dir.join(format!("{stem}.json"));
    let mut n = 1;
    while path.exists() {
        n += 1;
        path = dir.join(format!("{stem}-{n}.json"));
    }
    write_json(&path, capture)?;
    Ok(path)
}

/// `(timestamp prefix, endpoint, collision suffix)` — newest first means the highest
/// timestamp, and within one second the highest `-N` suffix.
fn sort_key(path: &Path) -> (String, String, u32) {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default();
    let (ts, rest) = stem.split_at(stem.len().min(15));
    let rest = rest.trim_start_matches('-');
    let (endpoint, n) = match rest.rsplit_once('-') {
        Some((e, n)) if n.chars().all(|c| c.is_ascii_digit()) && !n.is_empty() => {
            (e.to_string(), n.parse().unwrap_or(1))
        }
        _ => (rest.to_string(), 1),
    };
    (ts.to_string(), endpoint, n)
}

/// Captures newest first.
pub fn list_captures(root: &Path, provider: Provider) -> anyhow::Result<Vec<PathBuf>> {
    let dir = captures_dir(root, provider);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Ok(Vec::new());
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    files.sort_by_key(|p| sort_key(p));
    files.reverse();
    Ok(files)
}

/// The newest capture, optionally of one endpoint.
pub fn latest_capture(
    root: &Path,
    provider: Provider,
    endpoint: Option<&str>,
) -> anyhow::Result<Option<PathBuf>> {
    let files = list_captures(root, provider)?;
    Ok(files.into_iter().find(|p| match endpoint {
        Some(name) => p
            .file_stem()
            .and_then(|s| s.to_str())
            .is_some_and(|s| s.ends_with(&format!("-{name}")) || s.contains(&format!("-{name}-"))),
        None => true,
    }))
}

pub fn golden_path(root: &Path, provider: Provider, endpoint: &str) -> PathBuf {
    golden_dir(root, provider).join(format!("{endpoint}.json"))
}

pub fn documented_path(root: &Path, provider: Provider, endpoint: &str) -> PathBuf {
    documented_dir(root, provider).join(format!("{endpoint}.json"))
}

/// Promote a reviewed capture to `golden/<endpoint>.json` (re-scrubbed defensively).
pub fn bless(root: &Path, provider: Provider, from: &Path) -> anyhow::Result<PathBuf> {
    let mut capture = read_capture(from)?;
    if capture.provider != provider.id() {
        bail!(
            "{} is a {} capture, not {}",
            from.display(),
            capture.provider,
            provider.id()
        );
    }
    scrub_capture(&mut capture, provider.rules());
    let endpoint = endpoint_name(&capture);
    if endpoint == "other" {
        bail!(
            "{} {} is not an endpoint the {} rules know — add it to the provider module first",
            capture.request.method,
            capture.request.path(),
            provider.id()
        );
    }
    let path = golden_path(root, provider, endpoint);
    write_json(&path, &capture)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_the_fixtures_root_above_the_crate() {
        let here = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let root = fixtures_root_from(&here).expect("repo root");
        assert!(root.ends_with("tests/fixtures/fingerprints"));
        assert!(fixtures_root_from(Path::new("/")).is_none());
    }

    #[test]
    fn writes_never_overwrite_and_list_newest_first() {
        let tmp = tempfile::tempdir().unwrap();
        let mut capture = Provider::Claude.documented().remove(0);
        capture.captured_at = "2026-09-11T10:00:00Z".into();
        let first = write_capture(tmp.path(), &capture).unwrap();
        let second = write_capture(tmp.path(), &capture).unwrap();
        capture.captured_at = "2026-09-11T11:00:00Z".into();
        let third = write_capture(tmp.path(), &capture).unwrap();
        assert!(first.ends_with("claude/captures/20260911-100000-messages.json"));
        assert!(second.ends_with("20260911-100000-messages-2.json"));
        let listed = list_captures(tmp.path(), Provider::Claude).unwrap();
        assert_eq!(listed, vec![third.clone(), second, first]);
        assert_eq!(
            latest_capture(tmp.path(), Provider::Claude, Some("messages")).unwrap(),
            Some(third.clone())
        );
        assert_eq!(
            latest_capture(tmp.path(), Provider::Claude, Some("models")).unwrap(),
            None
        );
        let golden = bless(tmp.path(), Provider::Claude, &third).unwrap();
        assert!(golden.ends_with("claude/golden/messages.json"));
        assert_eq!(
            read_capture(&golden).unwrap().request.url,
            capture.request.url
        );
        assert!(bless(tmp.path(), Provider::Chatgpt, &third).is_err());
    }
}
