/** Typed loader for the JSON fixture sets in tests/fixtures/<name>/. */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import type {
  AITask,
  BlueyMode,
  ContextSnapshot,
  DetectedEventType,
  OCRContext,
  ResponseSchemaId,
  ResponseType,
  TranscriptSegment,
} from "@/lib/types";
import RUST_BUILT_IN_MODES from "../rust/built-in-modes.json";

export const FIXTURE_NAMES = [
  "interview",
  "behavioral",
  "coding",
  "system-design",
  "sales",
  "meeting",
  "lecture",
] as const;

export type FixtureName = (typeof FIXTURE_NAMES)[number];

/** The built-in mode each scenario runs in. */
const FIXTURE_MODE_IDS: Record<FixtureName, string> = {
  interview: "interview",
  behavioral: "behavioral-interview",
  coding: "coding-interview",
  "system-design": "system-design",
  sales: "sales",
  meeting: "team-meeting",
  lecture: "lecture",
};

/**
 * A built-in mode exactly as Rust defines it: `tests/fixtures/rust/` is
 * generated by `bluey-core/tests/ts_fixtures.rs`, which fails on drift.
 */
export function rustBuiltInMode(id: string): BlueyMode {
  const mode = (RUST_BUILT_IN_MODES as BlueyMode[]).find((m) => m.id === id);
  if (!mode) throw new Error(`no built-in mode "${id}" in tests/fixtures/rust/built-in-modes.json`);
  return mode;
}

/** Every built-in mode as Rust defines it, in seed order. */
export function rustBuiltInModes(): BlueyMode[] {
  return RUST_BUILT_IN_MODES as BlueyMode[];
}

export interface FixtureExpected {
  /** Explicit typed instruction for the ask, when the fixture uses one. */
  instruction?: string;
  task: AITask;
  schemaId: ResponseSchemaId;
  responseType: ResponseType;
  visionRequired: boolean;
  detectedEventType: DetectedEventType;
  requiresResponse: boolean;
}

export interface Fixture {
  name: FixtureName;
  transcript: TranscriptSegment[];
  ocr: OCRContext;
  mode: BlueyMode;
  snapshot: ContextSnapshot;
  expected: FixtureExpected;
}

function readJson<T>(name: FixtureName, file: string): T {
  // vitest cwd is the project root; import.meta.url is not reliable across
  // its transform pipeline, so resolve from cwd.
  const path = join(process.cwd(), "tests", "fixtures", name, file);
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

export function loadFixture(name: FixtureName): Fixture {
  return {
    name,
    transcript: readJson<TranscriptSegment[]>(name, "transcript.json"),
    ocr: readJson<OCRContext>(name, "ocr.json"),
    mode: rustBuiltInMode(FIXTURE_MODE_IDS[name]),
    snapshot: readJson<ContextSnapshot>(name, "snapshot.json"),
    expected: readJson<FixtureExpected>(name, "expected.json"),
  };
}

export function loadAllFixtures(): Fixture[] {
  return FIXTURE_NAMES.map((name) => loadFixture(name));
}
